export const CONTENT = [
  {
    id: "senna",
    title: "Senna",
    year: 2024,
    format: "Série",
    genres: ["Esporte", "Drama", "Biografia"],
    tags: ["automobilismo", "competição", "brasil"],
    popularity: 93,
    accent: "#e50914",
    gradient: "linear-gradient(145deg,#7f1017 0%,#e50914 52%,#1a1a1a 100%)",
    glyph: "S"
  },
  {
    id: "drive-to-survive",
    title: "F1: Dirigir para Viver",
    year: 2019,
    format: "Série documental",
    genres: ["Esporte", "Documentário"],
    tags: ["automobilismo", "competição", "bastidores"],
    popularity: 91,
    accent: "#ff2b2b",
    gradient: "linear-gradient(145deg,#111827 0%,#b91c1c 58%,#ef4444 100%)",
    glyph: "F1"
  },
  {
    id: "beckham",
    title: "Beckham",
    year: 2023,
    format: "Minissérie",
    genres: ["Esporte", "Documentário", "Biografia"],
    tags: ["futebol", "carreira", "bastidores"],
    popularity: 84,
    accent: "#4ade80",
    gradient: "linear-gradient(145deg,#052e16 0%,#166534 55%,#86efac 100%)",
    glyph: "⚽"
  },
  {
    id: "last-dance",
    title: "Arremesso Final",
    year: 2020,
    format: "Minissérie",
    genres: ["Esporte", "Documentário", "Biografia"],
    tags: ["basquete", "competição", "carreira"],
    popularity: 88,
    accent: "#f97316",
    gradient: "linear-gradient(145deg,#431407 0%,#c2410c 55%,#fb923c 100%)",
    glyph: "🏀"
  },
  {
    id: "stranger-things",
    title: "Stranger Things",
    year: 2016,
    format: "Série",
    genres: ["Ficção científica", "Fantasia", "Drama"],
    tags: ["mistério", "amizade", "sobrenatural"],
    popularity: 98,
    accent: "#f43f5e",
    gradient: "linear-gradient(145deg,#14030a 0%,#5f071d 56%,#e11d48 100%)",
    glyph: "ST"
  },
  {
    id: "black-mirror",
    title: "Black Mirror",
    year: 2011,
    format: "Série",
    genres: ["Ficção científica", "Drama", "Thriller"],
    tags: ["tecnologia", "distopia", "sociedade"],
    popularity: 90,
    accent: "#60a5fa",
    gradient: "linear-gradient(145deg,#020617 0%,#172554 52%,#3b82f6 100%)",
    glyph: "BM"
  },
  {
    id: "dark",
    title: "Dark",
    year: 2017,
    format: "Série",
    genres: ["Ficção científica", "Mistério", "Drama"],
    tags: ["tempo", "mistério", "família"],
    popularity: 89,
    accent: "#a78bfa",
    gradient: "linear-gradient(145deg,#111827 0%,#312e81 54%,#7c3aed 100%)",
    glyph: "D"
  },
  {
    id: "the-witcher",
    title: "The Witcher",
    year: 2019,
    format: "Série",
    genres: ["Fantasia", "Ação", "Drama"],
    tags: ["aventura", "monstros", "magia"],
    popularity: 87,
    accent: "#d1d5db",
    gradient: "linear-gradient(145deg,#0f172a 0%,#334155 55%,#94a3b8 100%)",
    glyph: "W"
  },
  {
    id: "bridgerton",
    title: "Bridgerton",
    year: 2020,
    format: "Série",
    genres: ["Romance", "Drama"],
    tags: ["época", "relacionamentos", "sociedade"],
    popularity: 94,
    accent: "#f9a8d4",
    gradient: "linear-gradient(145deg,#3b0a2a 0%,#9d174d 55%,#f9a8d4 100%)",
    glyph: "B"
  },
  {
    id: "the-crown",
    title: "The Crown",
    year: 2016,
    format: "Série",
    genres: ["Drama", "Histórico", "Biografia"],
    tags: ["realeza", "política", "história"],
    popularity: 86,
    accent: "#eab308",
    gradient: "linear-gradient(145deg,#1c1917 0%,#713f12 55%,#facc15 100%)",
    glyph: "♛"
  },
  {
    id: "money-heist",
    title: "La Casa de Papel",
    year: 2017,
    format: "Série",
    genres: ["Crime", "Thriller", "Drama"],
    tags: ["assalto", "estratégia", "grupo"],
    popularity: 96,
    accent: "#ef4444",
    gradient: "linear-gradient(145deg,#1f0a0a 0%,#991b1b 55%,#ef4444 100%)",
    glyph: "$"
  },
  {
    id: "narcos",
    title: "Narcos",
    year: 2015,
    format: "Série",
    genres: ["Crime", "Drama", "Biografia"],
    tags: ["investigação", "história", "crime"],
    popularity: 88,
    accent: "#d6d3d1",
    gradient: "linear-gradient(145deg,#1c1917 0%,#57534e 55%,#a8a29e 100%)",
    glyph: "N"
  },
  {
    id: "wednesday",
    title: "Wandinha",
    year: 2022,
    format: "Série",
    genres: ["Fantasia", "Comédia", "Mistério"],
    tags: ["escola", "sobrenatural", "humor"],
    popularity: 97,
    accent: "#c084fc",
    gradient: "linear-gradient(145deg,#120d18 0%,#581c87 54%,#c084fc 100%)",
    glyph: "W"
  },
  {
    id: "our-planet",
    title: "Nosso Planeta",
    year: 2019,
    format: "Documentário",
    genres: ["Documentário", "Natureza"],
    tags: ["planeta", "animais", "sustentabilidade"],
    popularity: 82,
    accent: "#22c55e",
    gradient: "linear-gradient(145deg,#052e16 0%,#047857 54%,#4ade80 100%)",
    glyph: "🌎"
  },
  {
    id: "chefs-table",
    title: "Chef's Table",
    year: 2015,
    format: "Série documental",
    genres: ["Documentário", "Gastronomia"],
    tags: ["comida", "criatividade", "cultura"],
    popularity: 76,
    accent: "#fb923c",
    gradient: "linear-gradient(145deg,#2b1205 0%,#9a3412 55%,#fb923c 100%)",
    glyph: "✦"
  },
  {
    id: "love-is-blind",
    title: "Casamento às Cegas",
    year: 2020,
    format: "Reality",
    genres: ["Reality", "Romance"],
    tags: ["relacionamentos", "experimento", "convívio"],
    popularity: 81,
    accent: "#f472b6",
    gradient: "linear-gradient(145deg,#3b0825 0%,#9d174d 55%,#f472b6 100%)",
    glyph: "♥"
  },
  {
    id: "cobra-kai",
    title: "Cobra Kai",
    year: 2018,
    format: "Série",
    genres: ["Ação", "Drama", "Comédia"],
    tags: ["luta", "competição", "amizade"],
    popularity: 85,
    accent: "#facc15",
    gradient: "linear-gradient(145deg,#1c1917 0%,#854d0e 55%,#facc15 100%)",
    glyph: "CK"
  },
  {
    id: "squid-game",
    title: "Round 6",
    year: 2021,
    format: "Série",
    genres: ["Thriller", "Drama", "Ação"],
    tags: ["competição", "sobrevivência", "sociedade"],
    popularity: 99,
    accent: "#ec4899",
    gradient: "linear-gradient(145deg,#140910 0%,#831843 52%,#ec4899 100%)",
    glyph: "○△□"
  },
  {
    id: "lizzie-mcguire",
    title: "Lizzie McGuire",
    year: 2001,
    format: "Série",
    genres: ["Comédia", "Família", "Drama"],
    tags: ["hilary-duff", "adolescência", "escola"],
    popularity: 96,
    accent: "#f472b6",
    gradient: "linear-gradient(145deg,#3a0b35 0%,#b83280 52%,#f9a8d4 100%)",
    glyph: "LM"
  },
  {
    id: "lizzie-mcguire-movie",
    title: "Lizzie McGuire: Um Sonho Popstar",
    year: 2003,
    format: "Filme",
    genres: ["Comédia", "Família", "Romance"],
    tags: ["hilary-duff", "viagem", "música"],
    popularity: 94,
    accent: "#f59e0b",
    gradient: "linear-gradient(145deg,#2b1646 0%,#c2418a 48%,#f5b942 100%)",
    glyph: "ROMA"
  },
  {
    id: "cadet-kelly",
    title: "Cadete Kelly",
    year: 2002,
    format: "Filme",
    genres: ["Comédia", "Família", "Drama"],
    tags: ["hilary-duff", "escola", "disciplina"],
    popularity: 84,
    accent: "#60a5fa",
    gradient: "linear-gradient(145deg,#07192e 0%,#1e3a5f 55%,#5aa4d8 100%)",
    glyph: "★"
  },
  {
    id: "agent-cody-banks",
    title: "O Agente Teen",
    year: 2003,
    format: "Filme",
    genres: ["Ação", "Comédia", "Família"],
    tags: ["hilary-duff", "espionagem", "aventura"],
    popularity: 81,
    accent: "#38bdf8",
    gradient: "linear-gradient(145deg,#050b16 0%,#0e4f72 52%,#e05283 100%)",
    glyph: "ACB"
  },
  {
    id: "cheaper-by-the-dozen",
    title: "Doze é Demais",
    year: 2003,
    format: "Filme",
    genres: ["Comédia", "Família"],
    tags: ["hilary-duff", "família", "anos-2000"],
    popularity: 91,
    accent: "#fb923c",
    gradient: "linear-gradient(145deg,#3a1707 0%,#b45309 54%,#f6ad55 100%)",
    glyph: "12"
  },
  {
    id: "a-cinderella-story",
    title: "A Nova Cinderela",
    year: 2004,
    format: "Filme",
    genres: ["Romance", "Comédia", "Drama"],
    tags: ["hilary-duff", "adolescência", "romance"],
    popularity: 98,
    accent: "#93c5fd",
    gradient: "linear-gradient(145deg,#101633 0%,#4459a6 50%,#f7b7d2 100%)",
    glyph: "✦"
  },
  {
    id: "raise-your-voice",
    title: "Na Trilha da Fama",
    year: 2004,
    format: "Filme",
    genres: ["Drama", "Música", "Romance"],
    tags: ["hilary-duff", "música", "adolescência"],
    popularity: 88,
    accent: "#a78bfa",
    gradient: "linear-gradient(145deg,#1c1236 0%,#6d3e9b 54%,#c084fc 100%)",
    glyph: "♪"
  },
  {
    id: "the-perfect-man",
    title: "Paixão de Aluguel",
    year: 2005,
    format: "Filme",
    genres: ["Romance", "Comédia", "Família"],
    tags: ["hilary-duff", "romance", "família"],
    popularity: 85,
    accent: "#fb7185",
    gradient: "linear-gradient(145deg,#38101d 0%,#a9365d 55%,#fb9eb5 100%)",
    glyph: "PM"
  },
  {
    id: "cheaper-by-the-dozen-2",
    title: "Doze é Demais 2",
    year: 2005,
    format: "Filme",
    genres: ["Comédia", "Família"],
    tags: ["hilary-duff", "família", "férias"],
    popularity: 84,
    accent: "#f59e0b",
    gradient: "linear-gradient(145deg,#351707 0%,#9a4f08 54%,#e8b44d 100%)",
    glyph: "12²"
  },
  {
    id: "material-girls",
    title: "Material Girls",
    year: 2006,
    format: "Filme",
    genres: ["Comédia", "Romance"],
    tags: ["hilary-duff", "irmãs", "anos-2000"],
    popularity: 83,
    accent: "#f9a8d4",
    gradient: "linear-gradient(145deg,#3d102c 0%,#b83280 52%,#f6d365 100%)",
    glyph: "MG"
  },
  {
    id: "younger",
    title: "Younger",
    year: 2015,
    format: "Série",
    genres: ["Comédia", "Drama", "Romance"],
    tags: ["hilary-duff", "carreira", "nova-york"],
    popularity: 93,
    accent: "#ec4899",
    gradient: "linear-gradient(145deg,#19051b 0%,#8b1d68 52%,#ec65a8 100%)",
    glyph: "Y"
  },
  {
    id: "how-i-met-your-father",
    title: "How I Met Your Father",
    year: 2022,
    format: "Série",
    genres: ["Comédia", "Romance", "Drama"],
    tags: ["hilary-duff", "amizade", "relacionamentos"],
    popularity: 92,
    accent: "#818cf8",
    gradient: "linear-gradient(145deg,#12152f 0%,#4f46a5 52%,#e879b9 100%)",
    glyph: "HIMYF"
  }
];

export const INTERACTION_LABELS = {
  seed: "Escolheu no início",
  preview: "Assistiu 10 min",
  finish: "Assistiu até o fim",
  like: "Gostei",
  love: "Amei",
  dislike: "Não é para mim",
  abandon: "Abandonou"
};

export const INTERACTION_WEIGHTS = {
  seed: 2.5,
  preview: 1.2,
  finish: 3.2,
  like: 4.2,
  love: 6.2,
  dislike: -5.5,
  abandon: -2.3
};
